### ISSUE TITLE
ENOENT error for valid proto files

### ISSUE THREAD

**Issue by trusktr** [mapbox/pbf#114]
I've been using protobufjs and other tools for other languages, and everything is working great so far.

I wanted to try swapping protobufjs for pbf, but pbf has an issue with the proto files.

At the top of one of my files, I have

```proto
syntax = "proto3";

package foo.models.v1;

import "foo/models/v1/Common.proto";
```

but then when I run `./node_modules/.bin/pbf ./foo/models/v1/test.proto > example.js` I get an error:

```
❯ ./node_modules/.bin/pbf ./foo/models/v1/test.proto > example.js
internal/fs/utils.js:220
    throw err;
    ^

Error: ENOENT: no such file or directory, open '/Users/trusktr/src/test-data-models/foo/models/v1/foo/models/v1/Common.proto'
    at Object.openSync (fs.js:440:3)
    at Object.readFileSync (fs.js:342:35)
    at readSync (/Users/trusktr/src/test-data-models/node_modules/resolve-protobuf-schema/index.js:14:23)
    at /Users/trusktr/src/test-data-models/node_modules/resolve-protobuf-schema/index.js:18:22
    at Array.forEach (<anonymous>)
    at Function.readSync [as sync] (/Users/trusktr/src/test-data-models/node_modules/resolve-protobuf-schema/index.js:17:11)
    at Object.<anonymous> (/Users/trusktr/src/test-data-models/node_modules/pbf/bin/pbf:13:32)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/Users/trusktr/src/test-data-models/foo/models/v1/foo/models/v1/Common.proto'
}
```

As you can see, it is repeating part of the path twice (`foo/models/v1/foo/models/v1`).

These proto files have worked perfectly for us with protobufjs (and other tools for the other languages) fine for the past couple of years, so this makes me wonder if there's something about the proto spec that `pbf` isn't following.

Any ideas? Looking forward to trying pbf out once I can get around this issue.

**Comment by trusktr** [comment]
Seems like the issue may be in resolve-protobuf-schema, considering that `pbf` uses that. Opened the issue there: https://github.com/mafintosh/resolve-protobuf-schema/issues/10

**Comment by predictwise** [comment]
Hi @trusktr,

I release the vector tiles(.pbf) by using Geoserver, but I have no idea how to generate a .proto file. Where does your proto file come from?

Oliver
